### ISSUE TITLE
Offer options from SynBioHub when creating a component

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Annotator#18]
We'll probably want to use many components multiple times, particularly the proteins and inducers from test harnesses (e.g., Doxycycline, GFP).

Once somebody has logged into SynBioHub, when they're creating a component, it should be possible for the system to reach out to SynBioHub, check if the desired component (or something similar) exists, and offer it to link instead of creating from scratch.

**Comment by bchan** [comment]
Offering options added by: 17dcb52. Not yet able to add components to the dictionary.
