### ISSUE TITLE
Organize example material away from code and docs

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Annotator#2]
The repository currently has everything mixed together at its top level. The example material should be organized away from code and documentation. Example material should also all be appropriately credited and ensure that usage is approved.

**Comment by jakebeal** [comment]
@bchan1298 please review and close if completed.

**Comment by bchan** [comment]
Only left BBa_K808000.gb as the example material, which is an iGEM part. Updated README to reflect this.
