### ISSUE TITLE
A Jupyter widget could not be displayed

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Annotator#5]
When re-opening the notebook on my Mac, I get the following instead of each user interface widget: 

> A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.

Re-running the code will bring the widgets back, but their saved state is clearly non-viable in some way.

**Comment by bchan** [comment]
This is resolved with the Initialization Cells nbextension. The upload button is a separate extension as well, so I'm not sure if it would be better to put instructions to install extensions into the README or to have a shell script automatically install them all.

**Comment by jakebeal** [comment]
How easy is it to install extensions? Is it like python libraries, where there is some equivalent of `pip install whatever` and it generally just does the right thing?  If so and there's just a few dependencies to install, then maybe it can just be in the README.  If there's more complexity to either the installation or the decision of what to install, however, it would be better to have  script.

**Comment by bchan** [comment]
There's a bit more to it than python libraries in that you have to manually enable the extension with a command as well. I'll add an issue to make a script, so I don't forget.

**Comment by jakebeal** [comment]
The new issue is #21 
Please test to make sure this is working, then close.

**Comment by bchan** [comment]
Resolved by: e2a6843
