### ISSUE TITLE
Missing widget for reading in SBOL file

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Annotator#6]
For some reason, under "Reading in the SBOL File", I do not get a blank for reading it in.

**Comment by bchan** [comment]
Expected functionality as the displays for the widgets are commented out.

**Comment by jakebeal** [comment]
Does this mean the displays are back in, or that we don't need the displays?  If we need them and they aren't yet back in, we should leave this open as a reminder to put them back in.

**Comment by bchan** [comment]
Not sure if we'll need them because if the user is uploading the GenBank, it will automatically read in the generated SBOL files. Would it be better to have that there or automatically read in the SBOL files?

**Comment by jakebeal** [comment]
If the GenBank gets automatically loaded, that's fine.
