### ISSUE TITLE
Designate device and testing sub-modules

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Annotator#8]
Most characterization systems will consist of much more than the device under test itself. In addition, there will be the test fixture for manipulating its inputs and quantifying its outputs, and the vectors used to carry the components.

As such, it should be possible to designate whether components belong to the device, the test fixture, or the vector context.  Note that not every part of a genetic construct will be covered by components, so by default non-component basepairs are part of the vector context.

Recommended implementation: instead of 1 ModuleDefinition, a nested set of 3 ModuleDefinitions: `Device-Test-Context` contains `Device-Test` contains `Device`.

Interactions will belong to the outermost module involved.  Thus, an AraC-->pBAD interaction would be on the Device, while the GFP production reporting its activity would be on Device-Test.

**Comment by bchan** [comment]
I am not sure if this is correct thinking, but here is the picture of the plasmids on the wall. The plasmid on the left and the one on the right would be a part of the `Device-Test`, and the `Device` would be the plasmid on the left. Then the whole thing would be the `Device-Test-Context`. The functional components of the top module (`Device-Test-Context`) are the specific coding sequence, promoters, and the other interacting components in blue. Would that be correct?

![IMG_6099](https://user-images.githubusercontent.com/23318120/60119089-a64e4700-974b-11e9-9834-6ed1461d93a5.png)

**Comment by jakebeal** [comment]
I would draw the borders differently, as follows:
- Everything in green and blue goes into a `Device` --- that includes ComponentDefinitions for portions of both plasmids, plus the rtTA protein, Dox small molecule, compound, and interactions involving them. The user might name this device something like "Dox sensor".
- `Device-Test` would have `Device` plus the mCherry coding sequence, the mCherry protein, and the production interaction.  This is the Dox sensor test.  It would have a Module (for `Device`) and three FunctionalComponents: mCherry, the mCherry coding sequence, and pTRE-mCherry (a ComponentDefinition that tells us the ordering of the pTRE promoter and the mCherry coding sequence)
- `Device-Test-Context` would then add the two plasmids as well, giving the genetic context of CAT-rtTA and of pTRE-mCherry

**Comment by bchan** [comment]
Fixed by: b710529
